## 利用GitHub Actions每天定时写入日志 ##

name: pages
on:
  push:
  schedule:
    - cron: '0 23 * * *' # 每5分钟一次，测试用

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:      
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        env: 
          GITHUB_TOKEN: ${{ secrets.AC_TOKENS }}      
        # run: ls # yarn && yarn pages # 运行目录是仓库根目录